#!/usr/bin/env bash

calc_sum() {
    sum="$(md5 ./index.rb)$(md5 ./app.js)$(md5 ./main.css)"
}

calc_sum

previous_sum=$sum

while true
do
    sleep 1

    calc_sum

    if [ "$sum" != "$previous_sum" ]
    then
        ./build
        previous_sum="$sum"
    fi
done
